kind: Service
apiVersion: v1
metadata:
  name: dotnetapp
  labels:
    app: dotnet
spec:
  selector:
    app: dotnet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp
  labels:
    app: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dotnetapp"
        dapr.io/app-port: "3000"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: dotnet
        image: dotnet:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Never
        resources:
          limits:
            memory: 512Mi
            cpu: "1"