controller:
  service:
    labels:
      purpose: "dapr-api-gateway"
  # Use a special class to not clash with any other controllers installed
  ingressClass: "dapr"

  # This Dapr-izes the workload
  podAnnotations:
    dapr.io/enabled: "true"
    dapr.io/app-id: "api-gateway"
    dapr.io/app-port: "80"